blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired



class PostForm(FlaskForm):
    title = StringField('Title * :', validators=[DataRequired()])
    content = TextAreaField('Contenu * :', validators=[DataRequired()])
    submit =  SubmitField("Publier")

blog/posts/routes.py
#posts/route.py va contenir toutes les routes relatives a l'application posts

from flask import render_template, url_for, flash, redirect, session, abort, request, Blueprint

from blog import db
from blog.posts.forms import PostForm
from blog.models import Post

#pour controler certaine routes (rendre des routes visible qu'à la connexion de l'utilisateur et e)
from flask_login import current_user, login_required


posts = Blueprint('posts', __name__)




#pour créer un nouveau post
@posts.route("/post/new", methods = ["GET", "POST"])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title = form.title.data, content = form.content.data, author = current_user)
        db.session.add(post)
        db.session.commit()
        flash("Votre post à été publié ", "success")
        return redirect(url_for("posts.post", post_id=post.id))
    image = url_for('static', filename='img/' + current_user.image_file)
    return render_template('create_post.html', title = "Nouveau post", form = form, image = image)

#pour voir un post en entier
@posts.route("/post/<post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)



#pour faire la mise a jour d'un post
#la mise a jour du post est possible si c'est le user qui a publié se post
@posts.route("/post/<post_id>/update", methods = ["GET", "POST"])
@login_required
def update_post(post_id):
    try:
        post = Post.query.get_or_404(post_id)
        form = PostForm()
        image = url_for('static', filename='img/' + current_user.image_file)

        #verification si l'auteur du post est la personne connecté
        if post.author != current_user:
            abort(403)
        if form.validate_on_submit():
            post.title = form.title.data
            post.content = form.content.data
            db.session.commit()
            flash("Post modifié avec succèss", "success")
            return redirect(url_for("posts.post", post_id=post.id))
        elif request.method == "GET":
            form.title.data = post.title
            form.content.data = post.content
        return render_template('update_post.html', title="Mise à jour du post", image = image, post=post, form = form)
    
    except AttributeError as e:
        flash("Veuillez vous connecter", "danger")
        return redirect(url_for('users.login'))

#pour supprimer un post
#la suppression du post est possible si c'est le user qui a publié se post
@posts.route("/post/<post_id>/delete", methods = ["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("Post supprimé avec succès", "success")
    return redirect (url_for('main.home'))

blog/users/routes.py
#users/route.py va contenir toutes les route relatives a l'application users


from flask import render_template, url_for, flash, redirect, session, abort, request, Blueprint

from blog import bcrypt, db, mail
from blog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, ResetPasswordForm, RequestResetForm
from blog.models import User, Post



#pour controler certaine routes (rendre des routes visible qu'à la connexion de l'utilisateur)
from flask_login import login_user, current_user, login_required, logout_user

from flask_mail import Message 
from blog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)




@users.route('/register', methods=['GET', 'POST'])
def register():
    
    #Controleur si un utilisateur est deja connecté il ne peut plus s'enregister 
    if current_user.is_authenticated:
        flash("Vous aviez déja un compte", "danger")
        return redirect(url_for("main.home"))

    form = RegistrationForm()
    if form.validate_on_submit():
        pw_hash = bcrypt.generate_password_hash(form.password.data) #cryptage du mot de passe du user
        user = User(
            username = form.username.data,
            email = form.email.data,
            password = pw_hash
        )
        db.session.add(user)
        db.session.commit()
        
        flash("Votre compte à été créé avec succès, veuillez vous connecter", 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title="s'enrégistrer", form = form)


@users.route('/login', methods=['GET', 'POST'])
def login():

    #Controleur si un utilisateur est deja connecté il ne peut plus ce connecter a nouveau
    #il faut qu'il se deconnecte d'abord
    if current_user.is_authenticated:
        flash("Vous êtes déjà connecté ", "danger")
        return redirect(url_for("main.home"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            if bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user, remember=form.remember.data)
                flash("Bienvenue {}".format(user.username), 'success')
              
                return redirect (request.args.get("next") or url_for("main.home"))
            else:
                flash("Mot de passe incorrect, veuillez reessayer", 'danger')
        else:
            flash("E-mail incorrect, veuillez reessayer", 'danger')
    return render_template('login.html',form = form, title="se connecter")


@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("users.login"))


@users.route("/account/update", methods = ["GET", "POST"])
@login_required
def account_update():
    form = UpdateAccountForm()
    if form.validate_on_submit():

        #la condition pour la modification de l'image d'utilisation
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Mise a jour de votre profil effectuée avec succès", "success")
        return redirect(url_for("users.account"))
    
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    # le schemin ou le dossier contenant les images 
    image = url_for('static', filename='img/' + current_user.image_file)
    return render_template('account_update.html', title = "Mise à jour de mon profil", image=image, form=form)

@users.route("/account", methods = ["GET", "POST"])
@login_required
def account():
    # le schemin ou le dossier contenant les images 
    image = url_for('static', filename='img/' + current_user.image_file)
    return render_template('account.html', title = "Mon profil", image=image)


#Pour voir tous les posts d'un utilisateur
@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)

#pour réinitialiser le mot de passe
@users.route("/reset_password", methods = ["POST", "GET"])
def reset_request():
    #Controleur si un utilisateur est deja connecté il ne peut plus ce connecter a nouveau
    #il faut qu'il se deconnecte d'abord
    if current_user.is_authenticated:
        flash("Vous êtes déjà connecté ", "danger")
        return redirect(url_for("main.home"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("Le lien de réinitialisation à été envoyé dans votre email", "success")
        return redirect(url_for('users.login'))

    return render_template('reset_request.html', form = form , title = 'Réinitialison du mot de passe')

@users.route("/reset_password/<token>", methods = ["POST", "GET"])
def reset_token(token):
    #Controleur si un utilisateur est deja connecté il ne peut plus ce connecter a nouveau
    #il faut qu'il se deconnecte d'abord
    if current_user.is_authenticated:
        flash("Vous êtes déjà connecté ", "danger")
        return redirect(url_for("main.home"))

    user = User.verify_reset_token(token)
    if user is None:
        flash("Votre token est expiré", "warning")
        return redirect(url_for('users.reset_request'))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        pw_hash = bcrypt.generate_password_hash(form.password.data) #cryptage du mot de passe du user
        user.password = pw_hash
        db.session.commit()
        flash("Mise à jour du mot de passe avec succès, veuillez vous connecter", 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', form = form , title = 'Réinitialison du mot de passe')

blog/templates/about.html
{% extends "layouts/base.html" %}
    {% block body %}
        {% for post in posts %}
            <h1>{{ post.title }}</h1>
            <h3>Publié par {{ post.auteur }} à {{post.date_posted}}</h3>
            <p>{{post.content}}</p>
        {% endfor %}
    {% endblock %}

blog/templates/account.html
{% extends "layouts/base.html" %}
    {% block body %}
    {% include 'layouts/_flashmsg.html' %}
        <div class="card mb-2">
            <div class="card-body">
                <div class="row border-bottom pb-3 mb-3">
                    <div class="col-3 col-lg-2 pt-0 px-0">
                        <img src="{{ image }}" width="100" height="100" alt="" class="rounded-circle">
                    </div>
                    <div class="col-9 col-lg-10 px-3">
                        <h4 >{{current_user.username}}</h4>
                        <p>{{current_user.email}}</p>
                    </div>
                </div>
                <div class="row  border-bottom">
                    <div class="col"><a href="{{url_for('posts.new_post')}}" type="button" class="btn btn-sm btn-warning font-weight-bold mb-3">Nouveau post</a></div>
                    <div class="col"><a href="{{url_for('users.user_posts', username = current_user.username ) }}" type="button" class="btn btn-sm btn-info font-weight-bold mb-3">Mes posts</a></div>
                
                </div>
                <div class="row justify-content-center mb-3 pt-3">
                    <div class="col-10">
                        <h3 class="text-info font-weight-bold text-center">Infos du compte</h3>
                        <hr>
                        <form>
                            <fieldset disabled>
                                <div class="form-group">
                                    <label for="disabledTextInput" class="font-weight-bold">Nom d'utilisateur :</label>
                                    <input type="text" id="disabledTextInput" class="form-control font-weight-bold" placeholder="{{current_user.username}}">
                                </div>
                                <div class="form-group">
                                    <label for="disabledTextInput" class="font-weight-bold">E-mail :</label>
                                    <input type="text" id="disabledTextInput" class="form-control font-weight-bold" placeholder="{{current_user.email}}">
                                </div>
                            </fieldset>
                        </form>
                        <a href="{{url_for('users.account_update')}}" type="button" class="btn btn-primary">Modifier</a>
                    </div>
                </div>
            </div>        
        </div>
    {% endblock %}

blog/templates/account_update.html
{% extends "layouts/base.html" %}
    {% block body %}
    {% include 'layouts/_flashmsg.html' %}
        <div class="card mb-2">
            <div class="card-body">
                <div class="row">
                    <div class="col-3 col-lg-2 pt-0 px-0">
                        <img src="{{ image }}" width="100" height="100" alt="" class="rounded-circle">
                    </div>
                    <div class="col-9 col-lg-10 px-3">
                        <h4 >{{current_user.username}}</h4>
                        <p>{{current_user.email}}</p>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-10">
                    <h3 class="text-info font-weight-bold text-center">Infos du compte</h3>
                    <hr>
                    <form action="{{url_for('users.account_update')}}" method="POST" enctype="multipart/form-data">
                        {{ form.hidden_tag() }}
                        <div class="form-group">
                            {{ form.username.label (class="font-weight-bold text-danger")}}
                            {{ form.username (class="form-control")}} 
                            <small id="usernameHelp" class="form-text text-muted">Saisir votre nouveau nom d'utilisateur.</small>
                                {% if form.username.errors %}
                                    <div class=errors>
                                        {% for error in form.username.errors %}
                                            <div class="text-danger font-italic">{{ error }}</div>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.email.label (class="font-weight-bold text-danger")}}
                            {{ form.email (class="form-control")}} 
                            <small id="emailHelp" class="form-text text-muted">Saisir une nouvelle addresse E-mail fonctionnelle.</small>
                                {% if form.email.errors %}
                                    <div class=errors>
                                        {% for error in form.email.errors %}
                                            <div class="text-danger font-italic">{{ error }}</div>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.picture.label (class="font-weight-bold text-danger")}}
                            {{ form.picture (class="form-control")}} 
                            <small id="emailHelp" class="form-text text-muted">Sélectionner une image dans votre ordi ('jpg', 'jpeg', 'png', 'gif').</small>
                                {% if form.picture.errors %}
                                    <div class=errors>
                                        {% for error in form.picture.errors %}
                                            <div class="text-danger font-italic">{{ error }}</div>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                        </div>
                        {{ form.submit (class="btn btn-outline-info font-weight-bold mb-3")}}
                        <a href="{{url_for('users.account')}}" type="button" class="float-right btn btn-outline-warning font-weight-bold mb-3">Annuler</a>
                    </form>
                </div>
            </div>
        
        </div>
    {% endblock %}

blog/templates/create_post.html
{% extends "layouts/base.html" %}
    {% block body %}
    {% include 'layouts/_flashmsg.html' %}
        <div class="card mb-2">
            <div class="card-body">
                <div class="row border-bottom pb-3 mb-3">
                    <div class="col-3 col-lg-2 pt-0 px-0">
                        <img src="{{ image }}" width="100" height="100" alt="" class="rounded-circle">
                    </div>
                    <div class="col-9 col-lg-10 px-3">
                        <h4 >{{current_user.username}}</h4>
                        <p>{{current_user.email}}</p>
                    </div>
                </div>
                <div class="row  border-bottom">
                    <div class="col"><a href="{{url_for('posts.new_post')}}" type="button" class="btn btn-sm btn-warning font-weight-bold mb-3">Nouveau post</a></div>
                    <div class="col"><a href="{{url_for('users.user_posts', username = current_user.username ) }}" type="button" class="btn btn-sm btn-info font-weight-bold mb-3">Mes posts</a></div>
                </div>
                <div class="row justify-content-center mb-3 pt-3">
                    <div class="col-10">
                        <h3 class="text-info font-weight-bold text-center">Nouveau post</h3>
                        <hr>
                        <form action="{{url_for('posts.new_post')}}" method="POST" enctype="multipart/form-data">
                            {{ form.hidden_tag() }}
                            <div class="form-group">
                                {{ form.title.label (class="font-weight-bold text-danger")}}
                                {{ form.title (class="form-control")}} 
                                    {% if form.title.errors %}
                                        <div class=errors>
                                            {% for error in form.title.errors %}
                                                <div class="text-danger font-italic">{{ error }}</div>
                                            {% endfor %}
                                        </div>
                                    {% endif %}
                            </div>
                            <div class="form-group">
                                {{ form.content.label (class="font-weight-bold text-danger")}}
                                {{ form.content (class="form-control", rows="11")}} 
                                    {% if form.content.errors %}
                                        <div class=errors>
                                            {% for error in form.content.errors %}
                                                <div class="text-danger font-italic">{{ error }}</div>
                                            {% endfor %}
                                        </div>
                                    {% endif %}
                            </div>
                            {{ form.submit (class="btn btn-outline-info font-weight-bold mb-3")}}
                            <a href="{{url_for('users.account')}}" type="button" class="float-right btn btn-outline-warning font-weight-bold mb-3">Annuler</a>
                        </form>
                    </div>
                </div>
            </div>        
        </div>
    {% endblock %}

blog/templates/index.html
{% extends "layouts/base.html" %}
    {% block body %}
    {% include 'layouts/_flashmsg.html' %}
    {% if posts %}
        {% for post in posts.items %}
            <div class="card mb-3">
                <div class="card-body">
                    <div class="row">
                        <div class="col-2 col-lg-1 pt-0 px-0">
                            <img src="{{ url_for('static', filename='img/' + post.author.image_file) }}" width="65" height="65" alt="" class="rounded-circle">
                        </div>
                        <div class="col-10 col-lg-11 px-3 px-lg-3">
                            <a href="{{url_for('users.user_posts', username = post.author.username ) }}" class="lead font-weight-bold" data-toggle="tooltip" data-placement="bottom" title="Voir tous les posts de {{ post.author.username | capitalize }}">{{ post.author.username | capitalize }}</a>
                            <small>Publié le {{ post.date_posted.strftime('%d-%m-%Y') }}</small>
                            <hr>
                            <h2><a href="{{ url_for('posts.post', post_id=post.id) }}" style="color: black;">{{ post.title }}</a></h2>
                            <p class="text-justify">{{ post.content | truncate(250) }}</p>
                            <a href="{{ url_for('posts.post', post_id=post.id) }}" class="btn btn-info mb-0">Lire plus</a>
                        </div>
                    </div>
                </div>        
            </div>
        {% endfor %}
    {% else %}
        <div class="card mb-3">
            <div class="card-body">
                <div class="row pb-3 mb-3">
                    <div class="col-12">
                        <h1 class="lead font-weight-bold text-center">Le blog ne contient pas posts</h1>
                    </div>
                </div>
            </div>        
        </div>
    {% endif %}
    <div class="text-center mb-3">
        {% for page_num in posts.iter_pages(left_edge = 1, right_edge = 1, left_current = 1, right_current = 2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info btn-sm" href="{{url_for('main.home', page = page_num )}}">{{page_num}}</a>
            {% else %}
                <a class="btn btn-outline-info btn-sm" href="{{url_for('main.home', page = page_num )}}">{{page_num}}</a>
            {% endif %}
        {% else %}
        ...
        {% endif%}
    {% endfor %}
    </div>
    {% endblock %}

blog/templates/login.html
{% extends "layouts/base.html" %}
{% block body %}
{% include 'layouts/_flashmsg.html' %}
<div class="card mb-2 pt-2">
    <div class="row justify-content-center">
        <div class="col-10">
            <h3 class="text-info font-bold text-center">Se connecter</h3>
            <hr>
            <form action="{{url_for('users.login')}}" method="POST">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.email.label (class="font-weight-bold")}}
                    {{ form.email (class="form-control")}} 
                        {% if form.email.errors %}
                            <div class=errors>
                                {% for error in form.email.errors %}
                                    <div class="text-danger font-italic">{{ error }}</div>
                                {% endfor %}
                            </div>
                        {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label (class="font-weight-bold")}}
                    {{ form.password (class="form-control")}} 
                        {% if form.password.errors %}
                            <div class=errors>
                                {% for error in form.password.errors %}
                                    <div class="text-danger font-italic">{{ error }}</div>
                                {% endfor %}
                            </div>
                        {% endif %}
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <div class="form-check">
                            {{ form.remember (class="form-check-input")}}
                            {{ form.remember.label (class="form-check-label font-weight-bold")}}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <a href="{{ url_for('users.reset_request') }}" class="float-right">
                            Mot de passe oublié?
                        </a>
                    </div>
                </div>
                
                {{ form.submit (class="btn btn-outline-info font-weight-bold mb-3")}}
            </form>
        </div>
        <div class="col-10 border-top pt-3 pb-3 text-center">
            <small >Si vous n'aviez pas encore de compte : <a href="{{url_for('users.register')}}">Cliquez ici</a> </small>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/post.html
{% extends "layouts/base.html" %}
    {% block body %}
    {% include 'layouts/_flashmsg.html' %}
        <div class="card mb-3">
            <div class="card-body">
                <div class="row pb-3 mb-3">
                    <div class="col-2 col-lg-1 pt-0 px-0">
                        <img src="{{ url_for('static', filename='img/' + post.author.image_file) }}" width="65" height="65" alt="" class="rounded-circle">
                    </div>
                    <div class="col-10 col-lg-11 px-0 px-lg-3">
                        <a href="{{url_for('users.user_posts', username = post.author.username ) }}" class="lead font-weight-bold" data-toggle="tooltip" data-placement="bottom" title="Voir tous les posts de {{ post.author.username | capitalize }}">{{ post.author.username | capitalize }}</a>
                        <small>Publié le {{ post.date_posted.strftime('%d-%m-%Y') }}</small>
                        {% if current_user == post.author %}
                            <a type="button" href="{{url_for('posts.update_post', post_id=post.id)}}" class="btn btn-danger btn-sm float-right" data-toggle="modal" data-target="#deleteBackdrop">Supprimer</a>
                            <a href="{{url_for('posts.update_post', post_id=post.id)}}" class="btn btn-warning mx-3 btn-sm float-right">Modifier</a>
                        {% endif %}
                        <hr>
                        <div>
                            <h2>{{ post.title }}</h2>
                            <p class="text-justify">{{ post.content }}</p>
                            <a href="{{url_for('main.home')}}" class="btn btn-info btn-sm mb-0">Retour</a>
                            {% if current_user == post.author %}
                            <a type="button" href="{{url_for('posts.update_post', post_id=post.id)}}" class="btn btn-danger btn-sm float-right" data-toggle="modal" data-target="#deleteBackdrop">Supprimer</a>
                            <a href="{{url_for('posts.update_post', post_id=post.id)}}" class="btn btn-warning mx-3 btn-sm float-right">Modifier</a>
                            <!-- Modal -->
                            <div class="modal fade" id="deleteBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="deleteBackdropLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="deleteBackdrop">Voulez-vous supprimer ce post ?</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-footer bg-info">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <form action="{{url_for('posts.delete_post', post_id = post.id)}}" method="POST">
                                            <input type="submit" class="btn btn-danger" value="supprimer">
                                        </form>
                                    </div>
                                </div>
                                </div>
                            </div>
                            {% endif %} 
                        </div>
                    </div>
                </div>
            </div>        
        </div>
    {% endblock %}

blog/templates/register.html
{% extends "layouts/base.html" %}


{% block body %}
{% include 'layouts/_flashmsg.html' %}
<div class="card mb-2 pt-2">
    <div class="row justify-content-center">
        <div class="col-10">
            <h3 class="text-info font-bold text-center">S'enregistrer</h3>
            <hr>
            <form action="{{url_for('users.register')}}" method="POST">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.username.label (class="font-weight-bold text-danger")}}
                    {{ form.username (class="form-control")}} 
                    <small id="usernameHelp" class="form-text text-muted">Saisir votre nom d'utilisateur.</small>
                        {% if form.username.errors %}
                            <div class=errors>
                                {% for error in form.username.errors %}
                                    <div class="text-danger font-italic">{{ error }}</div>
                                {% endfor %}
                            </div>
                        {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label (class="font-weight-bold text-danger")}}
                    {{ form.email (class="form-control")}} 
                    <small id="emailHelp" class="form-text text-muted">Saisir une addresse E-mail fonctionnelle.</small>
                        {% if form.email.errors %}
                            <div class=errors>
                                {% for error in form.email.errors %}
                                    <div class="text-danger font-italic">{{ error }}</div>
                                {% endfor %}
                            </div>
                        {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label (class="font-weight-bold text-danger")}}
                    {{ form.password (class="form-control")}} 
                    <small id="passwordlHelp" class="form-text text-muted">Saisir un mot de passe compris entre 8 - 25 caractères.</small>
                        {% if form.password.errors %}
                            <div class=errors>
                                {% for error in form.password.errors %}
                                    <div class="text-danger font-italic">{{ error }}</div>
                                {% endfor %}
                            </div>
                        {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password_confir.label (class="font-weight-bold text-danger")}}
                    {{ form.password_confir (class="form-control")}} 
                    <small id="password_confirHelp" class="form-text text-muted">Resaisir le mot de passe.</small>
                        {% if form.password_confir.errors %}
                            <div class=errors>
                                {% for error in form.password_confir.errors %}
                                    <div class="text-danger font-italic">{{ error }}</div>
                                {% endfor %}
                            </div>
                        {% endif %}
                </div>
                {{ form.submit (class="btn btn-outline-info font-weight-bold mb-3")}}
            </form>
        </div>
        <div class="col-10 border-top pt-3 pb-3 text-center">
            <small >Si vous aviez déja un compte : <a href="{{url_for('users.login')}}">Cliquez ici</a> </small>
        </div>
    </div>
</div>

{% endblock %}