blog/main/routes.py
#main/route.py va contenir toutes les routes relatives a notre site général


from flask import Blueprint, url_for, request,render_template
from blog.models import Post

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('index.html', posts=posts)

blog/posts/routes.py
#posts/route.py va contenir toutes les routes relatives a l'application posts

from flask import render_template, url_for, flash, redirect, session, abort, request, Blueprint

from blog import db
from blog.posts.forms import PostForm
from blog.models import Post

#pour controler certaine routes (rendre des routes visible qu'à la connexion de l'utilisateur et e)
from flask_login import current_user, login_required


posts = Blueprint('posts', __name__)




#pour créer un nouveau post
@posts.route("/post/new", methods = ["GET", "POST"])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title = form.title.data, content = form.content.data, author = current_user)
        db.session.add(post)
        db.session.commit()
        flash("Votre post à été publié ", "success")
        return redirect(url_for("posts.post", post_id=post.id))
    image = url_for('static', filename='img/' + current_user.image_file)
    return render_template('create_post.html', title = "Nouveau post", form = form, image = image)

#pour voir un post en entier
@posts.route("/post/<post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)



#pour faire la mise a jour d'un post
#la mise a jour du post est possible si c'est le user qui a publié se post
@posts.route("/post/<post_id>/update", methods = ["GET", "POST"])
@login_required
def update_post(post_id):
    try:
        post = Post.query.get_or_404(post_id)
        form = PostForm()
        image = url_for('static', filename='img/' + current_user.image_file)

        #verification si l'auteur du post est la personne connecté
        if post.author != current_user:
            abort(403)
        if form.validate_on_submit():
            post.title = form.title.data
            post.content = form.content.data
            db.session.commit()
            flash("Post modifié avec succèss", "success")
            return redirect(url_for("posts.post", post_id=post.id))
        elif request.method == "GET":
            form.title.data = post.title
            form.content.data = post.content
        return render_template('update_post.html', title="Mise à jour du post", image = image, post=post, form = form)
    
    except AttributeError as e:
        flash("Veuillez vous connecter", "danger")
        return redirect(url_for('users.login'))

#pour supprimer un post
#la suppression du post est possible si c'est le user qui a publié se post
@posts.route("/post/<post_id>/delete", methods = ["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("Post supprimé avec succès", "success")
    return redirect (url_for('main.home'))

blog/users/routes.py
#users/route.py va contenir toutes les route relatives a l'application users


from flask import render_template, url_for, flash, redirect, session, abort, request, Blueprint

from blog import bcrypt, db, mail
from blog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, ResetPasswordForm, RequestResetForm
from blog.models import User, Post



#pour controler certaine routes (rendre des routes visible qu'à la connexion de l'utilisateur)
from flask_login import login_user, current_user, login_required, logout_user

from flask_mail import Message 
from blog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)




@users.route('/register', methods=['GET', 'POST'])
def register():
    
    #Controleur si un utilisateur est deja connecté il ne peut plus s'enregister 
    if current_user.is_authenticated:
        flash("Vous aviez déja un compte", "danger")
        return redirect(url_for("main.home"))

    form = RegistrationForm()
    if form.validate_on_submit():
        pw_hash = bcrypt.generate_password_hash(form.password.data) #cryptage du mot de passe du user
        user = User(
            username = form.username.data,
            email = form.email.data,
            password = pw_hash
        )
        db.session.add(user)
        db.session.commit()
        
        flash("Votre compte à été créé avec succès, veuillez vous connecter", 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title="s'enrégistrer", form = form)


@users.route('/login', methods=['GET', 'POST'])
def login():

    #Controleur si un utilisateur est deja connecté il ne peut plus ce connecter a nouveau
    #il faut qu'il se deconnecte d'abord
    if current_user.is_authenticated:
        flash("Vous êtes déjà connecté ", "danger")
        return redirect(url_for("main.home"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            if bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user, remember=form.remember.data)
                flash("Bienvenue {}".format(user.username), 'success')
              
                return redirect (request.args.get("next") or url_for("main.home"))
            else:
                flash("Mot de passe incorrect, veuillez reessayer", 'danger')
        else:
            flash("E-mail incorrect, veuillez reessayer", 'danger')
    return render_template('login.html',form = form, title="se connecter")


@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("users.login"))


@users.route("/account/update", methods = ["GET", "POST"])
@login_required
def account_update():
    form = UpdateAccountForm()
    if form.validate_on_submit():

        #la condition pour la modification de l'image d'utilisation
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Mise a jour de votre profil effectuée avec succès", "success")
        return redirect(url_for("users.account"))
    
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    # le schemin ou le dossier contenant les images 
    image = url_for('static', filename='img/' + current_user.image_file)
    return render_template('account_update.html', title = "Mise à jour de mon profil", image=image, form=form)

@users.route("/account", methods = ["GET", "POST"])
@login_required
def account():
    # le schemin ou le dossier contenant les images 
    image = url_for('static', filename='img/' + current_user.image_file)
    return render_template('account.html', title = "Mon profil", image=image)


#Pour voir tous les posts d'un utilisateur
@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)

#pour réinitialiser le mot de passe
@users.route("/reset_password", methods = ["POST", "GET"])
def reset_request():
    #Controleur si un utilisateur est deja connecté il ne peut plus ce connecter a nouveau
    #il faut qu'il se deconnecte d'abord
    if current_user.is_authenticated:
        flash("Vous êtes déjà connecté ", "danger")
        return redirect(url_for("main.home"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("Le lien de réinitialisation à été envoyé dans votre email", "success")
        return redirect(url_for('users.login'))

    return render_template('reset_request.html', form = form , title = 'Réinitialison du mot de passe')

@users.route("/reset_password/<token>", methods = ["POST", "GET"])
def reset_token(token):
    #Controleur si un utilisateur est deja connecté il ne peut plus ce connecter a nouveau
    #il faut qu'il se deconnecte d'abord
    if current_user.is_authenticated:
        flash("Vous êtes déjà connecté ", "danger")
        return redirect(url_for("main.home"))

    user = User.verify_reset_token(token)
    if user is None:
        flash("Votre token est expiré", "warning")
        return redirect(url_for('users.reset_request'))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        pw_hash = bcrypt.generate_password_hash(form.password.data) #cryptage du mot de passe du user
        user.password = pw_hash
        db.session.commit()
        flash("Mise à jour du mot de passe avec succès, veuillez vous connecter", 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', form = form , title = 'Réinitialison du mot de passe')

blog/templates/layouts/_flashmsg.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
  <div class=flashes>
  {% for category, message in messages %}
    <div class="alert alert-{{ category }} text-center h4 lead">{{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>  
  {% endfor %}
  </div>
{% endif %}
{% endwith %}

blog/templates/layouts/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--CSS Bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <!--Font awesome -->
    <script src="https://kit.fontawesome.com/a0c787f6a0.js" crossorigin="anonymous"></script>

    <!--Title-->
    {% if title %}
        <title>Blog - {{title}}</title>
    {% else %}
        <title>Tamigué dev Blog</title>
    {% endif %}
</head>
<body class="bg-light">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand font-weight-bold">Tamigué-dev Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="navbar-nav mr-auto">
                    <a href="{{ url_for('main.home') }}" class="nav-item nav-link font-weight-bold text-warning">Acceuil</a>
                </div>
                <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                        <a href="" class="nav-item nav-link text-warning">Bonjour <b class="text-white">{{ current_user.username }} !</b></a>
                        <a href="{{url_for('posts.new_post')}}" class="nav-item nav-link text-warning">Post</a>
                        <a href="{{url_for('users.account')}}" class="nav-item nav-link text-warning">Profil</a>
                        <a href="{{url_for('users.logout')}}" class="nav-item nav-link text-warning">Deconnexion</a>
                    {% else %}
                        <a href="{{url_for('users.login')}}" class="nav-item nav-link font-weight-bold text-warning">Se connecter</a>
                        <a href="{{url_for('users.register')}}" class="nav-item nav-link font-weight-bold text-warning">S'enregistrer</a>
                    {% endif%}
                </div>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="row mt-5 pt-4 d-flex justify-content-between">
            <div class="col-lg-8 col-md-7">
                {% block body %}
                {% endblock %}
            </div>
            <div class="col-lg-4 col-md-5">
                <div class="card mb-2">
                    <div class="card-body">
                        <h1 class="text-center lead text-warning font-weight-bold">Coronavirus (Covid-19)</h1>
                        <p class="lead">Les gestes barrières : se protéger et protéger les autres</p>
                    </div>

                    <div class="container">
                        <div class="row justify-content-center ">
                            <div class="col-11">
                                <div class="card mb-5">
                                    <ul class="list-group list-group-flush">
                                      <li class="list-group-item text-center" style="font-size: 15px;"> <i class="fas fa-people-arrows px-3 text-info fa-2x"></i><hr> Restez toujours à plus d’un mètre les uns des autres.</li>
                                      <li class="list-group-item text-center" style="font-size: 15px;"><i class="fas fa-hands-wash px-3 text-info fa-2x"></i><hr> Lavez-vous les mains très régulièrement (avec de l'eau et du savon, ou du gel hydro-alcoolique).</li>
                                      <li class="list-group-item text-center" style="font-size: 15px;"><i class="fas fa-head-side-mask px-3 text-info fa-2x"></i><hr>Portez un masque quand la distance d’un mètre ne peut pas être respectée</li>
                                      <li class="list-group-item text-center" style="font-size: 15px;"><i class="fas fa-head-side-cough-slash px-3 text-danger fa-2x"></i><hr>Toussez ou éternuez dans votre coude ou dans un mouchoir</li>
                                      <li class="list-group-item text-center" style="font-size: 15px;"><i class="fas fa-handshake-slash px-3 text-danger fa-2x"></i><hr>Saluez sans vous serrer la main, arrêtez les embrassades</li>
                                      <li class="list-group-item text-center" style="font-size: 15px;"><i class="fas fa-pump-soap px-3 text-info fa-2x"></i><hr>Utilisez du gel hydro-alcoolique</li>
                                      <li class="list-group-item text-center" style="font-size: 15px;"><i class="fas fa-box-tissue px-3 text-info fa-2x"></i><hr>Utilisez un mouchoir à usage unique et jetez-le dans une poubèlle</li>
                                      <li class="list-group-item text-center" style="font-size: 15px;"><i class="fas fa-hospital-user px-3 text-info fa-2x"></i><hr>Se rendre à l'hopital en  cas de symptôme du COVID-19 </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>  
    </div>
    <!-- Footer-->
    <footer class="bd-footer bg-dark text-muted">
        <div class="container">
            <div class="row d-flex justify-content-between">
                <div class="col-lg-8 col-md-7">
                    <div class="col text-center pt-2">
                        <a class="font-weight-bold text-white">Tamigué Dev</a>
                        <hr class="bg-white">               
                    </div>
                    <div class="col text-center mb-3">
                        <a href="" class="mr-3" data-toggle="tooltip" data-placement="top" title="Mon site WEB"><i class="fas fa-globe fa-2x text-white"></i></a>
                        <a href="" class="mr-3" data-toggle="tooltip" data-placement="top" title="Me contacter sur facebook"><i class="fab fa-facebook fa-2x text-primary"></i></a>
                        <a href="" class="mr-3" data-toggle="tooltip" data-placement="top" title="Me contacter sur Youtube"><i class="fab fa-youtube fa-2x text-danger"></i></a>
                        <a href="" class="mr-3" data-toggle="tooltip" data-placement="top" title="Me contacter sur Linkedin"><i class="fab fa-linkedin fa-2x text-info"></i></a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-5">
                    <div class="col text-center pt-2">
                        <a class="font-weight-bold text-white">Code Source du Blog</a>
                        <hr class="bg-white">               
                    </div>
                    <div class="col text-center mb-3">
                        <a href="" class="mr-3" data-toggle="tooltip" data-placement="top" title="Voir le code source sur GitLab"><i class="fab fa-gitlab fa-2x text-white"></i></a>
                        <a href="" class="mr-2" data-toggle="tooltip" data-placement="top" title="Voir le code source sur GitHub"><i class="fab fa-github fa-2x text-white"></i></a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col text-right text-warning mb-3">
                    <p>&copy; Copyright {{now.year}} - By SORO Tamigué Simon <b>(Tamigué Dev)</b></p>
                </div>
            </div>
        </div>  
    </footer>

    <!-- Links JS-->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</body>
</html>